/* ------------------------- Cədvəl Yaradılması ------------------------- */
/*
   `parts` cədvəli yaradılır.
   - `part_id`: Avtomatik artan unikal identifikator (Primary Key).
   - `part_name`: Hissənin adı (NULL ola bilməz).
   - `buy_price`: Hissənin alış qiyməti (0-dan böyük olmalıdır).
*/
CREATE TABLE parts (
    part_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    part_name VARCHAR2(255) NOT NULL,
    buy_price NUMBER(9,2) CHECK(buy_price > 0),
    PRIMARY KEY(part_id)
);

/* Nümunə 1: Yanlış məlumat əlavə etmə cəhdi (buy_price = 0) */
INSERT INTO parts(part_name, buy_price)
VALUES('HDD', 0);

/* Nəticə:
   - Xəta: `buy_price` 0-dan böyük olmalıdır.
   - Əməliyyat uğursuz olur.
*/

/* Cədvəli silib yenidən yaradırıq. */
DROP TABLE parts;

CREATE TABLE parts (
    part_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    part_name VARCHAR2(255) NOT NULL,
    buy_price NUMBER(9,2) CONSTRAINT check_positive_buy_price CHECK(buy_price > 0),
    PRIMARY KEY(part_id)
);

/* Nümunə 2: Yanlış məlumat əlavə etmə cəhdi (buy_price = -100) */
INSERT INTO parts(part_name, buy_price)
VALUES('Screen', -100);

/* Nəticə:
   - Xəta: `buy_price` 0-dan böyük olmalıdır.
   - Əməliyyat uğursuz olur.
*/

/* ------------------------- HR Employees Cədvəlinə Uyğunlaşdırma ------------------------- */
/*
   `employees` cədvəli üçün `salary` sütununa CHECK məhdudiyyəti əlavə edirik.
   - `salary`: İşçinin maaşı (0-dan böyük olmalıdır).
*/

/* Nümunə 3: `employees` cədvəlinə CHECK məhdudiyyəti əlavə etmək */
ALTER TABLE employees
ADD CONSTRAINT check_positive_salary CHECK (salary > 0);

/* Nəticə:
   - `salary` sütunu üçün yeni CHECK məhdudiyyəti əlavə edilir.
   - Maaş 0-dan böyük olmalıdır.
*/

/* Nümunə 4: CHECK məhdudiyyətini deaktiv etmək */
ALTER TABLE employees
DISABLE CONSTRAINT check_positive_salary;

/* Nəticə:
   - `check_positive_salary` məhdudiyyəti deaktiv edilir.
   - Artıq `salary` sütununa 0 və ya mənfi dəyərlər əlavə etmək mümkündür.
*/

/* Nümunə 5: CHECK məhdudiyyətini aktiv etmək */
ALTER TABLE employees
ENABLE CONSTRAINT check_positive_salary;

/* Nəticə:
   - `check_positive_salary` məhdudiyyəti aktiv edilir.
   - `salary` sütununa yalnız 0-dan böyük dəyərlər əlavə etmək mümkündür.
*/

/* ------------------------- HR Employees Cədvəlinə Məlumat Əlavə Etmə ------------------------- */
/*
   `employees` cədvəlinə yeni məlumatlar əlavə edirik.
   - `salary` sütunu üçün CHECK məhdudiyyəti aktivdir.
*/

/* Nümunə 6: Düzgün məlumat əlavə etmək */
INSERT INTO employees (employee_id, first_name, last_name, email, hire_date, job_id, salary)
VALUES (1001, 'Ali', 'Məmmədov', 'ali.mammadov@example.com', SYSDATE, 'IT_PROG', 5000);

/* Nəticə:
   - Məlumat uğurla əlavə edilir.
*/

/* Nümunə 7: Yanlış məlumat əlavə etmə cəhdi (salary = -1000) */
INSERT INTO employees (employee_id, first_name, last_name, email, hire_date, job_id, salary)
VALUES (1002, 'Ayşə', 'Quliyeva', 'ayse.quliyeva@example.com', SYSDATE, 'HR_REP', -1000);

/* Nəticə:
   - Xəta: `salary` 0-dan böyük olmalıdır.
   - Əməliyyat uğursuz olur.
*/